---
title: "Practica3"
author: "Marcial"
date: "01/19/2017"
output: html_document
editor_options: 
  chunk_output_type: console
---
1. Install and load packages

```{r, echo = F}
install.packages("picante")
#This will install also package dependences
library(picante)
#This will also load package dependences
#library(ape)
#library(vegan)
#library(permute)
#library(lattice)
#library(nlme)


```

2. Open your tree, edit and plot

```{r, echo = F}
mytree <- read.nexus("sequencedef.nex.con.tre")
#you may do this practice with also with the RAXML tree
#mytree <- read.tree("RAxML_bipartitions.sequencedef.tre")
mytree
plot(mytree)
plot(mytree, cex = 0.7)
nodelabels()
mytree <- root(mytree, node = 45)
mytree <- root(mytree, node = 45)
plot(mytree, cex = 0.5)

```


3. Open presence / absense matrix. Spring vs. Fall.

```{r}
mydata <- read.csv("mydata.csv")
mydata
rownames(mydata) = mydata[,1]

```

4. Calculate phylogenetic diversity statistics.

```{r, echo = F}
color.plot.phylo(mytree, mydata, "PRIMAVERA", "Species")
color.plot.phylo(mytree, mydata, "OTONO", "Species")
rownames(mydata) = mydata[,1]

?pd
#Explore the function and run the examples

rownames(mydata) = mydata[,1]

mypd <- pd(t(mydata[,-c(1)]), mytree, include.root=F)
mypd

?mpd
#Explore the function and run the examples

mympd <- mpd(t(mydata[,-c(1)]), cophenetic(mytree), abundance.weighted=T)
mympd
myresults1 <- cbind(mypd, mympd)

?mntd
#Explore the function and run the examples

mymntd <- mntd(t(mydata[,-c(1)]), cophenetic(mytree2), abundance.weighted=T)
mymntd
myresults2 <- cbind(myresults1, mymntd)
colnames(myresults2) <- c("PD", "SR", "MPD", "MNTD")
myresults2
write.table(myresults2, file = "diversity_index_results.txt")


```

5. Finally we are going to check for phylogenetic clustering and overdispersion
```{r, echo = F}
my.ses.pd <- ses.pd(t(mydata[,-c(1,2)]), mytree, include.root=F, null.model = "taxa.labels",
runs = 999)
my.ses.pd
write.table(my.ses.pd, file="ses.pd.result.txt")

my.ses.mpd <- ses.mpd(t(mydata[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mpd
write.table(my.ses.mpd, file="ses.mpd.result.txt")


my.ses.mntd <- ses.mntd(t(mydata[,-c(1,2)]), cophenetic(mytree), null.model = "taxa.labels",
abundance.weighted = T, runs = 999)
my.ses.mntd
write.table(my.ses.mntd, file="ses.mntd.result.txt")



comm.phylo.cor.r <- comm.phylo.cor(t(mydata[,-c(1,2)]), mytree, metric="cij",null.model="sample.taxa.labels", abundance.weighted = T)
comm.phylo.cor.r
par(mai=c(1.02,0.82,0.82,0.42))
hist(comm.phylo.cor.r$random.corrs)
abline(v=comm.phylo.cor.r$obs.corr)

```


